import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'system-ui', 'sans-serif'],
        display: ['Poppins', 'system-ui', 'sans-serif'],
        serif: ['Playfair Display', 'Georgia', 'serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'Courier New', 'monospace'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          50: '#f0f6ff',
          100: '#e4edff',
          200: '#cfdeff',
          300: '#b0c7ff',
          400: '#8ba3ff',
          500: '#6b7cff',
          600: '#5661ff',
          700: '#4147eb',
          800: '#353ac2',
          900: '#2f359b',
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          50: '#f5f7fa',
          100: '#e8edf3',
          200: '#d1dbe6',
          300: '#a3b7cc',
          400: '#7593b3',
          500: '#4d6f8c',
          600: '#3d5970',
          700: '#2d4355',
          800: '#1d2d39',
          900: '#0d171e',
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          50: '#fff0f0',
          100: '#ffdddd',
          500: '#ff4d4d',
          600: '#ff3333',
          700: '#cc0000',
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          50: '#2a2a2a',
          100: '#353535',
          200: '#404040',
          300: '#4a4a4a',
          400: '#555555',
          500: '#606060',
          600: '#6b6b6b',
          700: '#767676',
          800: '#818181',
          900: '#8c8c8c',
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          50: '#f3e7ff',
          100: '#e6d0ff',
          200: '#d1abff',
          300: '#bc86ff',
          400: '#a761ff',
          500: '#923cff',
          600: '#7d17ff',
          700: '#6b00eb',
          800: '#5900c2',
          900: '#47009b',
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      spacing: {
        xs: '0.25rem',     // 4px
        sm: '0.5rem',      // 8px
        md: '1rem',        // 16px
        lg: '1.5rem',      // 24px
        xl: '2rem',        // 32px
        '2xl': '2.5rem',   // 40px
        '3xl': '3rem',     // 48px
        '4xl': '3.5rem',   // 56px
        '5xl': '4rem',     // 64px
      },
      gap: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '1rem',
        lg: '1.5rem',
        xl: '2rem',
      },
      padding: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '1rem',
        lg: '1.5rem',
        xl: '2rem',
        '2xl': '2.5rem',
        '3xl': '3rem',
      },
      margin: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '1rem',
        lg: '1.5rem',
        xl: '2rem',
        '2xl': '2.5rem',
        '3xl': '3rem',
      },
      fontSize: {
        xs: ['clamp(0.75rem, 2vw, 0.875rem)', '1rem'],
        sm: ['clamp(0.875rem, 2.5vw, 1rem)', '1.25rem'],
        base: ['clamp(1rem, 2.5vw, 1.1rem)', '1.5rem'],
        lg: ['clamp(1.125rem, 3vw, 1.25rem)', '1.75rem'],
        xl: ['clamp(1.25rem, 3.5vw, 1.5rem)', '1.75rem'],
        '2xl': ['clamp(1.5rem, 4vw, 1.875rem)', '2rem'],
        '3xl': ['clamp(1.875rem, 4.5vw, 2.25rem)', '2.25rem'],
        '4xl': ['clamp(2.25rem, 5vw, 2.5rem)', '2.5rem'],
        '5xl': ['clamp(3rem, 6vw, 3.75rem)', '1'],
      },
      lineHeight: {
        tight: '1.2',
        normal: '1.5',
        relaxed: '1.75',
        loose: '2',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'fade-in': {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        'pulse-slow': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        'scale-in': { '0%': { transform: 'scale(0.95)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        'scale-in-strong': { '0%': { transform: 'scale(0.9)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        'scale-out': { '0%': { transform: 'scale(1)', opacity: '1' }, '100%': { transform: 'scale(0.95)', opacity: '0' } },
        'fade-in-down': { '0%': { opacity: '0', transform: 'translateY(-10px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'fade-out-up': { '0%': { opacity: '1', transform: 'translateY(0)' }, '100%': { opacity: '0', transform: 'translateY(-10px)' } },
        'scale-in-center': { '0%': { opacity: '0', transform: 'scale(0.8) translate(-50%, -50%)' }, '100%': { opacity: '1', transform: 'scale(1) translate(-50%, -50%)' } },
        'scale-out-center': { '0%': { opacity: '1', transform: 'scale(1) translate(-50%, -50%)' }, '100%': { opacity: '0', transform: 'scale(0.8) translate(-50%, -50%)' } },
        'dark-pulse': { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.7' } },
        'bounce-slow': { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-20px)' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in': 'fade-in 0.3s ease-out',
        'pulse-slow': 'pulse-slow 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'scale-in': 'scale-in 0.3s ease-out',
        'scale-in-strong': 'scale-in-strong 0.5s ease-out forwards',
        'scale-out': 'scale-out 0.3s ease-in',
        'fade-in-down': 'fade-in-down 0.3s ease-out',
        'fade-out-up': 'fade-out-up 0.3s ease-in',
        'scale-in-center': 'scale-in-center 0.5s cubic-bezier(0.4, 0, 0.2, 1)',
        'scale-out-center': 'scale-out-center 0.5s cubic-bezier(0.4, 0, 0.2, 1)',
        'dark-pulse': 'dark-pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-slow': 'bounce-slow 3s infinite',
      },
      boxShadow: {
        'dark-sm': '0 1px 3px 0 rgba(255, 255, 255, 0.1)',
        'dark-md': '0 4px 6px -1px rgba(255, 255, 255, 0.1), 0 2px 4px -1px rgba(255, 255, 255, 0.06)',
        'dark-lg': '0 10px 15px -3px rgba(255, 255, 255, 0.1), 0 4px 6px -2px rgba(255, 255, 255, 0.05)',
      },
      screens: {
        'xs': '320px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
        'touch': { 'raw': '(pointer: coarse)' },
        'pointer': { 'raw': '(pointer: fine)' },
        'landscape': { 'raw': '(orientation: landscape)' },
        'portrait': { 'raw': '(orientation: portrait)' },
      },
      maxWidth: {
        'xs': '20rem',
        'sm': '24rem',
        'md': '28rem',
        'lg': '32rem',
        'xl': '36rem',
        '2xl': '42rem',
        '3xl': '48rem',
        '4xl': '56rem',
        '5xl': '64rem',
        '6xl': '72rem',
        '7xl': '80rem',
        'full': '100%',
        'min': 'min-content',
        'max': 'max-content',
        'fit': 'fit-content',
      },
      minHeight: {
        'touch': '44px',
        'screen': '100vh',
        'screen-dynamic': '100dvh',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
