import type { KPIDefinition, ReportDefinition } from '@/types/reports';

export const KPI_DEFINITIONS: KPIDefinition[] = [
  {
    id: 'budget_utilization',
    name: 'Budget Utilization Rate',
    description: 'Percentage of total budget that has been spent',
    category: 'financial',
    unit: 'percentage',
    targetValue: 85,
    warningThreshold: 90,
    criticalThreshold: 100,
    higherIsBetter: false,
    calculationMethod: '(Total Spent / Total Budget) * 100',
  },
  {
    id: 'burn_rate',
    name: 'Monthly Burn Rate',
    description: 'Average monthly spending rate',
    category: 'financial',
    unit: 'currency',
    higherIsBetter: false,
    calculationMethod: 'Sum of monthly expenses / Number of months',
  },
  {
    id: 'cost_per_visit',
    name: 'Average Cost Per Site Visit',
    description: 'Average total cost incurred per completed site visit',
    category: 'financial',
    unit: 'currency',
    higherIsBetter: false,
    calculationMethod: 'Total Visit Costs / Completed Visits',
  },
  {
    id: 'pending_approvals_value',
    name: 'Pending Approvals Value',
    description: 'Total value of submissions awaiting approval',
    category: 'financial',
    unit: 'currency',
    higherIsBetter: false,
    calculationMethod: 'Sum of pending cost submissions',
  },
  {
    id: 'visit_completion_rate',
    name: 'Visit Completion Rate',
    description: 'Percentage of assigned visits that are completed',
    category: 'analytics',
    unit: 'percentage',
    targetValue: 95,
    warningThreshold: 80,
    criticalThreshold: 70,
    higherIsBetter: true,
    calculationMethod: '(Completed Visits / Assigned Visits) * 100',
  },
  {
    id: 'on_time_completion',
    name: 'On-Time Completion Rate',
    description: 'Percentage of visits completed before due date',
    category: 'analytics',
    unit: 'percentage',
    targetValue: 90,
    warningThreshold: 75,
    criticalThreshold: 60,
    higherIsBetter: true,
    calculationMethod: '(On-Time Completions / Total Completions) * 100',
  },
  {
    id: 'average_cycle_time',
    name: 'Average Cycle Time',
    description: 'Average time from assignment to completion',
    category: 'analytics',
    unit: 'days',
    targetValue: 3,
    warningThreshold: 5,
    criticalThreshold: 7,
    higherIsBetter: false,
    calculationMethod: 'Avg(Completion Date - Assignment Date)',
  },
  {
    id: 'enumerator_productivity',
    name: 'Enumerator Productivity',
    description: 'Average visits completed per enumerator per week',
    category: 'analytics',
    unit: 'count',
    targetValue: 10,
    warningThreshold: 5,
    criticalThreshold: 3,
    higherIsBetter: true,
    calculationMethod: 'Completed Visits / Active Enumerators / Weeks',
  },
  {
    id: 'sla_adherence',
    name: 'SLA Adherence Rate',
    description: 'Percentage of visits meeting SLA requirements',
    category: 'analytics',
    unit: 'percentage',
    targetValue: 95,
    warningThreshold: 85,
    criticalThreshold: 75,
    higherIsBetter: true,
    calculationMethod: '(SLA Met Visits / Total Visits) * 100',
  },
  {
    id: 'assignment_latency',
    name: 'Assignment Latency',
    description: 'Average time from MMP upload to visit assignment',
    category: 'analytics',
    unit: 'hours',
    targetValue: 24,
    warningThreshold: 48,
    criticalThreshold: 72,
    higherIsBetter: false,
    calculationMethod: 'Avg(Assignment Date - MMP Upload Date)',
  },
  {
    id: 'project_variance',
    name: 'Budget Variance',
    description: 'Difference between planned and actual spending',
    category: 'project_cost',
    unit: 'percentage',
    targetValue: 0,
    warningThreshold: 10,
    criticalThreshold: 20,
    higherIsBetter: false,
    calculationMethod: '((Actual - Planned) / Planned) * 100',
  },
  {
    id: 'forecast_accuracy',
    name: 'Forecast Accuracy',
    description: 'Accuracy of cost forecasts vs actual',
    category: 'project_cost',
    unit: 'percentage',
    targetValue: 95,
    warningThreshold: 85,
    criticalThreshold: 75,
    higherIsBetter: true,
    calculationMethod: '100 - |((Forecast - Actual) / Actual) * 100|',
  },
  {
    id: 'contingency_usage',
    name: 'Contingency Usage',
    description: 'Percentage of contingency budget used',
    category: 'project_cost',
    unit: 'percentage',
    targetValue: 0,
    warningThreshold: 50,
    criticalThreshold: 80,
    higherIsBetter: false,
    calculationMethod: '(Contingency Used / Contingency Total) * 100',
  },
  {
    id: 'override_rate',
    name: 'Budget Override Rate',
    description: 'Percentage of transactions requiring override',
    category: 'audit',
    unit: 'percentage',
    targetValue: 0,
    warningThreshold: 5,
    criticalThreshold: 10,
    higherIsBetter: false,
    calculationMethod: '(Override Count / Total Transactions) * 100',
  },
  {
    id: 'approval_cycle_time',
    name: 'Approval Cycle Time',
    description: 'Average time from submission to approval',
    category: 'audit',
    unit: 'hours',
    targetValue: 24,
    warningThreshold: 48,
    criticalThreshold: 72,
    higherIsBetter: false,
    calculationMethod: 'Avg(Approval Date - Submission Date)',
  },
  {
    id: 'compliance_score',
    name: 'Compliance Score',
    description: 'Overall compliance rating',
    category: 'audit',
    unit: 'percentage',
    targetValue: 100,
    warningThreshold: 90,
    criticalThreshold: 80,
    higherIsBetter: true,
    calculationMethod: '(Compliant Items / Total Items) * 100',
  },
  {
    id: 'data_quality_score',
    name: 'Data Quality Score',
    description: 'Overall data completeness and accuracy',
    category: 'audit',
    unit: 'percentage',
    targetValue: 98,
    warningThreshold: 95,
    criticalThreshold: 90,
    higherIsBetter: true,
    calculationMethod: '(Valid Records / Total Records) * 100',
  },
  {
    id: 'portfolio_health',
    name: 'Portfolio Health Score',
    description: 'Overall health of all projects',
    category: 'executive',
    unit: 'percentage',
    targetValue: 90,
    warningThreshold: 75,
    criticalThreshold: 60,
    higherIsBetter: true,
    calculationMethod: 'Weighted average of project health scores',
  },
  {
    id: 'field_coverage',
    name: 'Field Coverage Rate',
    description: 'Percentage of target sites covered',
    category: 'executive',
    unit: 'percentage',
    targetValue: 100,
    warningThreshold: 80,
    criticalThreshold: 60,
    higherIsBetter: true,
    calculationMethod: '(Covered Sites / Total Target Sites) * 100',
  },
  {
    id: 'escalation_backlog',
    name: 'Escalation Backlog',
    description: 'Number of pending escalations',
    category: 'executive',
    unit: 'count',
    targetValue: 0,
    warningThreshold: 5,
    criticalThreshold: 10,
    higherIsBetter: false,
    calculationMethod: 'Count of unresolved escalations',
  },
  {
    id: 'route_efficiency',
    name: 'Route Efficiency Score',
    description: 'Efficiency of travel routes based on distance and time',
    category: 'analytics',
    unit: 'percentage',
    targetValue: 85,
    warningThreshold: 70,
    criticalThreshold: 50,
    higherIsBetter: true,
    calculationMethod: '(Optimal Route Distance / Actual Distance) * 100',
  },
  {
    id: 'first_pass_rate',
    name: 'First Pass Acceptance Rate',
    description: 'Percentage of visits accepted on first submission',
    category: 'analytics',
    unit: 'percentage',
    targetValue: 90,
    warningThreshold: 80,
    criticalThreshold: 70,
    higherIsBetter: true,
    calculationMethod: '(First-Pass Accepts / Total Submissions) * 100',
  },
  {
    id: 'rework_rate',
    name: 'Rework Rate',
    description: 'Percentage of visits requiring rework/rejection',
    category: 'analytics',
    unit: 'percentage',
    targetValue: 5,
    warningThreshold: 10,
    criticalThreshold: 15,
    higherIsBetter: false,
    calculationMethod: '(Rework Required / Total Submissions) * 100',
  },
  {
    id: 'wallet_balance_health',
    name: 'Wallet Balance Health',
    description: 'Percentage of wallets with sufficient balance',
    category: 'financial',
    unit: 'percentage',
    targetValue: 95,
    warningThreshold: 85,
    criticalThreshold: 70,
    higherIsBetter: true,
    calculationMethod: '(Healthy Wallets / Total Wallets) * 100',
  },
  {
    id: 'withdrawal_processing_time',
    name: 'Withdrawal Processing Time',
    description: 'Average time to process withdrawals',
    category: 'financial',
    unit: 'hours',
    targetValue: 24,
    warningThreshold: 48,
    criticalThreshold: 72,
    higherIsBetter: false,
    calculationMethod: 'Avg(Completed Date - Request Date)',
  },
  {
    id: 'gps_accuracy_rate',
    name: 'GPS Accuracy Rate',
    description: 'Percentage of visits with high GPS accuracy',
    category: 'audit',
    unit: 'percentage',
    targetValue: 95,
    warningThreshold: 85,
    criticalThreshold: 75,
    higherIsBetter: true,
    calculationMethod: '(High Accuracy Visits / Total Visits) * 100',
  },
  {
    id: 'photo_completeness',
    name: 'Photo Documentation Rate',
    description: 'Percentage of visits with complete photo documentation',
    category: 'audit',
    unit: 'percentage',
    targetValue: 100,
    warningThreshold: 95,
    criticalThreshold: 90,
    higherIsBetter: true,
    calculationMethod: '(Complete Photo Sets / Total Visits) * 100',
  },
  {
    id: 'team_utilization',
    name: 'Team Utilization Rate',
    description: 'Percentage of team capacity being utilized',
    category: 'executive',
    unit: 'percentage',
    targetValue: 85,
    warningThreshold: 70,
    criticalThreshold: 50,
    higherIsBetter: true,
    calculationMethod: '(Active Assignments / Team Capacity) * 100',
  },
];

export const REPORT_DEFINITIONS: ReportDefinition[] = [
  {
    id: 'financial_summary',
    name: 'Financial Summary Report',
    description: 'Comprehensive overview of budget, expenses, and cash flow',
    category: 'financial',
    allowedRoles: ['Admin', 'SuperAdmin', 'SeniorOperationsLead', 'FinanceApprover', 'ProjectManager'],
    dataSource: 'budget_transactions, project_budgets, mmp_budgets',
    defaultFormat: 'pdf',
    availableFormats: ['pdf', 'excel', 'csv'],
    schedulable: true,
    kpiIds: ['budget_utilization', 'burn_rate', 'pending_approvals_value'],
  },
  {
    id: 'expense_breakdown',
    name: 'Expense Breakdown Report',
    description: 'Detailed breakdown of expenses by category, project, and period',
    category: 'financial',
    allowedRoles: ['Admin', 'SuperAdmin', 'SeniorOperationsLead', 'FinanceApprover', 'ProjectManager'],
    dataSource: 'cost_submissions, budget_transactions',
    defaultFormat: 'excel',
    availableFormats: ['pdf', 'excel', 'csv'],
    schedulable: true,
    kpiIds: ['cost_per_visit'],
  },
  {
    id: 'cash_flow',
    name: 'Cash Flow Report',
    description: 'Inflows and outflows over time with projections',
    category: 'financial',
    allowedRoles: ['Admin', 'SuperAdmin', 'SeniorOperationsLead', 'FinanceApprover'],
    dataSource: 'wallet_transactions, budget_transactions',
    defaultFormat: 'excel',
    availableFormats: ['pdf', 'excel', 'csv'],
    schedulable: true,
  },
  {
    id: 'budget_vs_actual',
    name: 'Budget vs Actual Report',
    description: 'Comparison of planned vs actual spending by project/MMP',
    category: 'financial',
    allowedRoles: ['Admin', 'SuperAdmin', 'SeniorOperationsLead', 'FinanceApprover', 'ProjectManager'],
    dataSource: 'project_budgets, mmp_budgets, budget_transactions',
    defaultFormat: 'pdf',
    availableFormats: ['pdf', 'excel', 'csv'],
    schedulable: true,
    kpiIds: ['project_variance'],
  },
  {
    id: 'enumerator_productivity',
    name: 'Enumerator Productivity Report',
    description: 'Performance metrics for all enumerators',
    category: 'analytics',
    allowedRoles: ['Admin', 'SuperAdmin', 'SeniorOperationsLead', 'ProjectManager', 'FOM', 'Supervisor'],
    dataSource: 'mmp_site_entries, profiles',
    defaultFormat: 'excel',
    availableFormats: ['pdf', 'excel', 'csv'],
    schedulable: true,
    kpiIds: ['enumerator_productivity', 'visit_completion_rate', 'on_time_completion'],
  },
  {
    id: 'operational_efficiency',
    name: 'Operational Efficiency Report',
    description: 'Overall operational metrics and SLA adherence',
    category: 'analytics',
    allowedRoles: ['Admin', 'SuperAdmin', 'SeniorOperationsLead', 'ProjectManager', 'FOM'],
    dataSource: 'mmp_site_entries, mmp_files',
    defaultFormat: 'pdf',
    availableFormats: ['pdf', 'excel', 'csv'],
    schedulable: true,
    kpiIds: ['average_cycle_time', 'sla_adherence', 'assignment_latency'],
  },
  {
    id: 'team_performance',
    name: 'Team Performance Report',
    description: 'Comparative performance across teams and individuals',
    category: 'analytics',
    allowedRoles: ['Admin', 'SuperAdmin', 'SeniorOperationsLead', 'ProjectManager', 'FOM', 'Supervisor'],
    dataSource: 'mmp_site_entries, profiles, wallets',
    defaultFormat: 'pdf',
    availableFormats: ['pdf', 'excel', 'csv'],
    schedulable: true,
  },
  {
    id: 'coverage_analysis',
    name: 'Geographic Coverage Report',
    description: 'Site coverage by state, hub, and locality',
    category: 'analytics',
    allowedRoles: ['Admin', 'SuperAdmin', 'SeniorOperationsLead', 'ProjectManager', 'FOM'],
    dataSource: 'mmp_site_entries, sites',
    defaultFormat: 'pdf',
    availableFormats: ['pdf', 'excel', 'csv'],
    schedulable: false,
    kpiIds: ['field_coverage'],
  },
  {
    id: 'project_cost_analysis',
    name: 'Project Cost Analysis Report',
    description: 'Detailed cost analysis per project with variance',
    category: 'project_cost',
    allowedRoles: ['Admin', 'SuperAdmin', 'SeniorOperationsLead', 'FinanceApprover', 'ProjectManager'],
    dataSource: 'projects, project_budgets, budget_transactions',
    defaultFormat: 'pdf',
    availableFormats: ['pdf', 'excel', 'csv'],
    schedulable: true,
    kpiIds: ['project_variance', 'forecast_accuracy'],
  },
  {
    id: 'cost_per_region',
    name: 'Regional Cost Report',
    description: 'Cost breakdown by geographic region',
    category: 'project_cost',
    allowedRoles: ['Admin', 'SuperAdmin', 'SeniorOperationsLead', 'FinanceApprover', 'ProjectManager'],
    dataSource: 'mmp_site_entries, cost_submissions',
    defaultFormat: 'excel',
    availableFormats: ['pdf', 'excel', 'csv'],
    schedulable: true,
  },
  {
    id: 'contingency_tracking',
    name: 'Contingency Tracking Report',
    description: 'Status and usage of contingency budgets',
    category: 'project_cost',
    allowedRoles: ['Admin', 'SuperAdmin', 'SeniorOperationsLead', 'FinanceApprover'],
    dataSource: 'project_budgets, budget_transactions',
    defaultFormat: 'pdf',
    availableFormats: ['pdf', 'excel', 'csv'],
    schedulable: true,
    kpiIds: ['contingency_usage'],
  },
  {
    id: 'forecast_report',
    name: 'Cost Forecast Report',
    description: 'Projected costs to completion',
    category: 'project_cost',
    allowedRoles: ['Admin', 'SuperAdmin', 'SeniorOperationsLead', 'FinanceApprover', 'ProjectManager'],
    dataSource: 'projects, project_budgets, mmp_site_entries',
    defaultFormat: 'pdf',
    availableFormats: ['pdf', 'excel', 'csv'],
    schedulable: true,
  },
  {
    id: 'audit_trail',
    name: 'Audit Trail Report',
    description: 'Complete transaction and action audit log',
    category: 'audit',
    allowedRoles: ['Admin', 'SuperAdmin', 'SeniorOperationsLead'],
    dataSource: 'audit_logs',
    defaultFormat: 'excel',
    availableFormats: ['pdf', 'excel', 'csv'],
    schedulable: true,
  },
  {
    id: 'override_log',
    name: 'Budget Override Log',
    description: 'All budget overrides with justifications',
    category: 'audit',
    allowedRoles: ['Admin', 'SuperAdmin', 'SeniorOperationsLead'],
    dataSource: 'audit_logs, budget_transactions',
    defaultFormat: 'pdf',
    availableFormats: ['pdf', 'excel', 'csv'],
    schedulable: true,
    kpiIds: ['override_rate'],
  },
  {
    id: 'compliance_dashboard',
    name: 'Compliance Status Report',
    description: 'Document validity, permits, and policy compliance',
    category: 'audit',
    allowedRoles: ['Admin', 'SuperAdmin', 'SeniorOperationsLead', 'ProjectManager'],
    dataSource: 'mmp_files, mmp_site_entries',
    defaultFormat: 'pdf',
    availableFormats: ['pdf', 'excel', 'csv'],
    schedulable: true,
    kpiIds: ['compliance_score'],
  },
  {
    id: 'data_quality',
    name: 'Data Quality Report',
    description: 'Data completeness, accuracy, and anomalies',
    category: 'audit',
    allowedRoles: ['Admin', 'SuperAdmin', 'ICT'],
    dataSource: 'all_tables',
    defaultFormat: 'pdf',
    availableFormats: ['pdf', 'excel', 'csv'],
    schedulable: true,
    kpiIds: ['data_quality_score'],
  },
  {
    id: 'executive_summary',
    name: 'Executive Summary Report',
    description: 'High-level overview for senior management',
    category: 'executive',
    allowedRoles: ['Admin', 'SuperAdmin', 'SeniorOperationsLead'],
    dataSource: 'all',
    defaultFormat: 'pdf',
    availableFormats: ['pdf', 'excel'],
    schedulable: true,
    kpiIds: ['portfolio_health', 'field_coverage', 'escalation_backlog'],
  },
  {
    id: 'portfolio_health',
    name: 'Portfolio Health Report',
    description: 'RAG status and health metrics for all projects',
    category: 'executive',
    allowedRoles: ['Admin', 'SuperAdmin', 'SeniorOperationsLead', 'ProjectManager'],
    dataSource: 'projects, project_budgets',
    defaultFormat: 'pdf',
    availableFormats: ['pdf', 'excel', 'csv'],
    schedulable: true,
    kpiIds: ['portfolio_health'],
  },
  {
    id: 'risk_register',
    name: 'Risk Register Report',
    description: 'Identified risks and mitigation status',
    category: 'executive',
    allowedRoles: ['Admin', 'SuperAdmin', 'SeniorOperationsLead', 'ProjectManager'],
    dataSource: 'projects, audit_logs',
    defaultFormat: 'pdf',
    availableFormats: ['pdf', 'excel', 'csv'],
    schedulable: true,
  },
  {
    id: 'escalation_summary',
    name: 'Escalation Summary Report',
    description: 'Pending and resolved escalations',
    category: 'executive',
    allowedRoles: ['Admin', 'SuperAdmin', 'SeniorOperationsLead'],
    dataSource: 'notifications, audit_logs',
    defaultFormat: 'pdf',
    availableFormats: ['pdf', 'excel', 'csv'],
    schedulable: true,
    kpiIds: ['escalation_backlog'],
  },
];

export function getKPIById(id: string): KPIDefinition | undefined {
  return KPI_DEFINITIONS.find(kpi => kpi.id === id);
}

export function getKPIsByCategory(category: string): KPIDefinition[] {
  return KPI_DEFINITIONS.filter(kpi => kpi.category === category);
}

export function getReportById(id: string): ReportDefinition | undefined {
  return REPORT_DEFINITIONS.find(report => report.id === id);
}

export function getReportsByCategory(category: string): ReportDefinition[] {
  return REPORT_DEFINITIONS.filter(report => report.category === category);
}

export function getReportsForRole(role: string): ReportDefinition[] {
  return REPORT_DEFINITIONS.filter(report => 
    report.allowedRoles.includes(role) || 
    report.allowedRoles.includes('Admin') ||
    role === 'SuperAdmin'
  );
}
