include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    use_super_parameters: true
    prefer_const_constructors: true

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
  exclude:
    - build/**
    - lib/firebase_options.dart
