-- Migration: Ensure projects.id has a UUID default
-- Run this in your Supabase SQL editor or via psql against the database that the app uses.

-- Ensure UUID extension is available
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- If id column is not uuid type, please review before running the ALTER TYPE statement below.
-- Set default to gen_random_uuid() so inserts without id will get a UUID generated by DB
ALTER TABLE public.projects
  ALTER COLUMN id SET DEFAULT gen_random_uuid();

-- Verify: you can run
-- SELECT column_default FROM information_schema.columns WHERE table_schema='public' AND table_name='projects' AND column_name='id';
