import { AlertTriangle, ArrowRight, CircleDollarSign, Info, ListChecks, Save, Settings2, ShieldCheck, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import type { Hub } from '@/context/location/LocationContext';
import type { IncentiveRole, IncentiveSplitMethod } from '@/types/incentive';
import { CONFIGURABLE_INCENTIVE_ROLES } from '@/types/incentive';

type Language = 'en' | 'ar';
type RoleRow = { role: IncentiveRole; isActive: boolean; bonusPct: number; splitMethod: IncentiveSplitMethod };
type HubOverride = { localId: string; hubId: string; role: IncentiveRole; bonusPct: number; toDelete: boolean };
const t = (language: Language, en: string, ar: string) => language === 'ar' ? ar : en;
const role = (language: Language, value: IncentiveRole) => ({
  coordinator: t(language, 'Coordinator', 'المنسق'),
  supervisor: t(language, 'Supervisor', 'المشرف'),
  fom: t(language, 'FOM', 'مدير العمليات الميدانية'),
  support_team: t(language, 'Support Team', 'فريق الدعم'),
}[value] ?? value);
const description = (language: Language, value: IncentiveRole) => ({
  coordinator: t(language, 'Automatic eligibility is derived from the staff profile role, additional role, or effective classification, scoped to this hub and a mapped state.', 'تُستمد الأهلية تلقائياً من دور ملف الموظف أو دوره الإضافي أو تصنيفه الساري، ضمن هذا المركز وولاية مرتبطة به.'),
  supervisor: t(language, 'Automatic eligibility is derived from the staff profile role, additional role, or effective classification, scoped to this hub.', 'تُستمد الأهلية تلقائياً من دور ملف الموظف أو دوره الإضافي أو تصنيفه الساري، ضمن هذا المركز.'),
  fom: t(language, 'Automatic eligibility is derived from the staff profile role, additional role, or effective classification, scoped to this hub.', 'تُستمد الأهلية تلقائياً من دور ملف الموظف أو دوره الإضافي أو تصنيفه الساري، ضمن هذا المركز.'),
  support_team: t(language, 'Manual eligibility only. Use the audited include rule below; this role is never inferred from a profile.', 'الأهلية يدوية فقط. استخدم قاعدة التضمين المدققة أدناه؛ لا يُستنتج هذا الدور أبداً من الملف الشخصي.'),
}[value] ?? '');

export function SettingsWorkspaceTranslated(props: {
  language: Language; coverageThreshold: number; setCoverageThreshold: (value: number) => void;
  globalRows: RoleRow[]; setGlobalRows: (value: RoleRow[] | ((rows: RoleRow[]) => RoleRow[])) => void;
  hubOverrides: HubOverride[]; setHubOverrides: (value: HubOverride[] | ((rows: HubOverride[]) => HubOverride[])) => void;
  hubs: Hub[]; newHub: string; setNewHub: (value: string) => void; newRole: IncentiveRole; setNewRole: (value: IncentiveRole) => void;
  newPct: number; setNewPct: (value: number) => void; warnings: string[]; save: () => void; saving: boolean;
}) {
  const { language, coverageThreshold, setCoverageThreshold, globalRows, setGlobalRows, hubOverrides, setHubOverrides, hubs, newHub, setNewHub, newRole, setNewRole, newPct, setNewPct, warnings, save, saving } = props;
  const visible = hubOverrides.filter(item => !item.toDelete);
  const addOverride = () => {
    if (!newHub || visible.some(item => item.hubId === newHub && item.role === newRole)) return;
    setHubOverrides(rows => [...rows, { localId: crypto.randomUUID(), hubId: newHub, role: newRole, bonusPct: newPct, toDelete: false }]);
    setNewHub('');
  };
  return <div className="space-y-6">
    <div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#178080]">{t(language, 'Future calculations', 'الاحتسابات المستقبلية')}</p><div className="mt-1 flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><h2 className="text-2xl font-bold">{t(language, 'Configure bonus rules', 'إعداد قواعد المكافآت')}</h2><p className="mt-1 max-w-2xl text-sm text-slate-600">{t(language, 'These rules are read when a new MMP incentive snapshot is calculated. Existing snapshots retain their recorded configuration.', 'تُقرأ هذه القواعد عند احتساب لقطة حوافز MMP جديدة. وتحتفظ اللقطات الحالية بإعداداتها المسجلة.')}</p></div><Button onClick={save} disabled={saving} className="bg-[#123942] hover:bg-[#1b4d57]"><Save className="me-2 h-4 w-4" />{saving ? t(language, 'Saving changes…', 'جارٍ حفظ التغييرات…') : t(language, 'Save changes', 'حفظ التغييرات')}</Button></div></div>
    {warnings.length > 0 && <div className="rounded-xl border border-[#ead7a1] bg-[#fff8df] p-4"><div className="flex items-center gap-2 text-sm font-semibold text-[#775d14]"><AlertTriangle className="h-4 w-4" />{t(language, 'Review before saving', 'راجع قبل الحفظ')}</div>{warnings.map(warning => <p key={warning} className="ms-6 mt-1 text-xs text-[#775d14]">{warning}</p>)}</div>}
    <div className="grid gap-6 xl:grid-cols-[1fr_360px]"><div className="space-y-6">
      <section className="rounded-xl border border-[#d8e5e1] bg-white p-5"><div className="flex items-start gap-3"><div className="rounded-lg bg-[#d8efea] p-2 text-[#167575]"><CircleDollarSign className="h-4 w-4" /></div><div><h3 className="font-semibold">{t(language, 'Eligibility gate', 'بوابة الأهلية')}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{t(language, 'An MMP must meet this WFP-confirmed coverage percentage before its bonus pool can be unlocked.', 'يجب أن يحقق MMP نسبة التغطية المؤكدة من WFP قبل فتح مجمّع مكافآته.')}</p></div></div><div className="mt-5 flex max-w-sm items-end gap-3"><div className="flex-1"><Label className="text-xs text-slate-500">{t(language, 'Minimum confirmed coverage', 'الحد الأدنى للتغطية المؤكدة')}</Label><Input className="mt-1.5" type="number" min={0} max={100} value={coverageThreshold} onChange={event => setCoverageThreshold(Math.max(0, Math.min(100, Number(event.target.value))))} /></div><span className="pb-2 text-sm font-semibold text-slate-500">%</span></div></section>
      <section className="overflow-hidden rounded-xl border border-[#d8e5e1] bg-white"><div className="border-b border-[#e5efec] px-5 py-4"><div className="flex items-center gap-2"><Settings2 className="h-4 w-4 text-[#178080]" /><h3 className="font-semibold">{t(language, 'Role rules', 'قواعد الأدوار')}</h3></div><p className="mt-1 text-xs text-slate-500">{t(language, 'The global rule applies unless a hub override is listed below.', 'تُطبّق القاعدة العامة ما لم يُدرج تجاوز خاص بالمركز أدناه.')}</p></div><div className="divide-y divide-[#edf3f1]">{globalRows.map(row => <div key={row.role} className="grid gap-4 px-5 py-4 sm:grid-cols-[1fr_auto_130px_170px] sm:items-center"><div><p className="font-medium">{role(language, row.role)}</p><p className="mt-0.5 text-xs leading-5 text-slate-500">{description(language, row.role)}</p></div><Switch aria-label={role(language, row.role)} checked={row.isActive} onCheckedChange={isActive => setGlobalRows(rows => rows.map(item => item.role === row.role ? { ...item, isActive } : item))} /><div><Label className="text-[10px] uppercase tracking-wider text-slate-400">{t(language, 'Bonus rate', 'نسبة المكافأة')}</Label><div className="mt-1 flex items-center gap-1"><Input className="h-9" type="number" step={0.5} disabled={!row.isActive} value={row.bonusPct} onChange={event => setGlobalRows(rows => rows.map(item => item.role === row.role ? { ...item, bonusPct: Number(event.target.value) } : item))} /><span className="text-sm text-slate-500">%</span></div></div><div><Label className="text-[10px] uppercase tracking-wider text-slate-400">{t(language, 'Pool distribution', 'توزيع المجمّع')}</Label><Select value={row.splitMethod} disabled={!row.isActive} onValueChange={(splitMethod: IncentiveSplitMethod) => setGlobalRows(rows => rows.map(item => item.role === row.role ? { ...item, splitMethod } : item))}><SelectTrigger className="mt-1 h-9"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="proportional">{t(language, 'Proportional', 'نسبي')}</SelectItem><SelectItem value="equal">{t(language, 'Equal share', 'حصة متساوية')}</SelectItem></SelectContent></Select></div></div>)}</div><div className="flex gap-2 border-t border-[#e5efec] bg-[#f7fbfa] px-5 py-3 text-xs text-slate-500"><Info className="h-4 w-4 shrink-0 text-[#178080]" /><span>{t(language, 'Proportional weights a share by the DC fee pool. Equal share divides eligible recipients evenly.', 'يوزّع النسبي الحصة بحسب مجمّع رسوم جامع البيانات. أما الحصة المتساوية فتقسم بين المستلمين المؤهلين بالتساوي.')}</span></div></section>
      <section className="overflow-hidden rounded-xl border border-[#d8e5e1] bg-white"><div className="border-b border-[#e5efec] px-5 py-4"><h3 className="font-semibold">{t(language, 'Hub-specific overrides', 'تجاوزات خاصة بالمركز')}</h3><p className="mt-1 text-xs text-slate-500">{t(language, 'Use sparingly for a hub and role that need a different rate.', 'استخدمها بحذر لمركز ودور يحتاجان إلى معدل مختلف.')}</p></div>{visible.length ? <div className="divide-y divide-[#edf3f1]">{visible.map(item => <div key={item.localId} className="flex flex-wrap items-center gap-3 px-5 py-3"><span className="min-w-[160px] flex-1 text-sm font-medium">{hubs.find(hub => hub.id === item.hubId)?.name ?? item.hubId}</span><span className="w-32 text-xs text-slate-500">{role(language, item.role)}</span><Input className="h-8 w-20" type="number" step={0.5} value={item.bonusPct} onChange={event => setHubOverrides(rows => rows.map(row => row.localId === item.localId ? { ...row, bonusPct: Number(event.target.value) } : row))} /><Button variant="ghost" size="icon" aria-label={t(language, 'Remove override', 'إزالة التجاوز')} className="text-red-600" onClick={() => setHubOverrides(rows => rows.filter(row => row.localId !== item.localId))}><Trash2 className="h-4 w-4" /></Button></div>)}</div> : <p className="px-5 py-6 text-sm text-slate-500">{t(language, 'No hub overrides. Global rules apply across all hubs.', 'لا توجد تجاوزات للمراكز. تُطبّق القواعد العامة على جميع المراكز.')}</p>}<div className="flex flex-wrap items-end gap-2 border-t border-[#e5efec] bg-[#f7fbfa] p-5"><div><Label className="text-[10px] uppercase tracking-wider text-slate-400">{t(language, 'Hub', 'المركز')}</Label><Select value={newHub} onValueChange={setNewHub}><SelectTrigger className="mt-1 h-9 w-44"><SelectValue placeholder={t(language, 'Select a hub', 'اختر مركزاً')} /></SelectTrigger><SelectContent>{hubs.map(hub => <SelectItem key={hub.id} value={hub.id}>{hub.name}</SelectItem>)}</SelectContent></Select></div><div><Label className="text-[10px] uppercase tracking-wider text-slate-400">{t(language, 'Role', 'الدور')}</Label><Select value={newRole} onValueChange={setNewRole}><SelectTrigger className="mt-1 h-9 w-36"><SelectValue /></SelectTrigger><SelectContent>{CONFIGURABLE_INCENTIVE_ROLES.map(item => <SelectItem key={item} value={item}>{role(language, item)}</SelectItem>)}</SelectContent></Select></div><div><Label className="text-[10px] uppercase tracking-wider text-slate-400">{t(language, 'Rate', 'المعدل')}</Label><Input className="mt-1 h-9 w-20" type="number" step={0.5} value={newPct} onChange={event => setNewPct(Number(event.target.value))} /></div><Button variant="outline" className="h-9" onClick={addOverride}>{t(language, 'Add override', 'إضافة تجاوز')}</Button></div></section>
    </div><aside className="space-y-4"><section className="rounded-xl bg-[#123942] p-5 text-white"><div className="flex items-center gap-2 text-[#a7d9cc]"><ListChecks className="h-4 w-4" /><h3 className="font-semibold">{t(language, 'How the workflow works', 'كيف يعمل سير العمل')}</h3></div><div className="mt-5 space-y-5">{[[t(language, 'Configure', 'الإعداد'), t(language, 'Save rules for future calculations.', 'احفظ القواعد للاحتسابات المستقبلية.')], [t(language, 'Calculate', 'الاحتساب'), t(language, 'The system checks coverage and builds a snapshot.', 'يتحقق النظام من التغطية وينشئ لقطة.')], [t(language, 'Pre-approve', 'الاعتماد المبدئي'), t(language, 'An administrator reviews recipients and exclusions.', 'يراجع المسؤول المستلمين والاستبعادات.')], [t(language, 'Approve and pay', 'الاعتماد والدفع'), t(language, 'Finance approves the locked snapshot and records payment.', 'يعتمد فريق المالية اللقطة المقفلة ويسجل الدفع.')]].map(([title, body], index) => <div key={title} className="flex gap-3"><span className="font-mono text-xs text-[#e9c46a]">0{index + 1}</span><div><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-[#c8ded9]">{body}</p>{index < 3 && <ArrowRight className="mt-3 h-3 w-3 rotate-90 text-[#6da89c]" />}</div></div>)}</div></section><section className="rounded-xl border border-[#d8e5e1] bg-white p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[#178080]" /><h3 className="font-semibold">{t(language, 'What is recorded', 'ما يتم تسجيله')}</h3></div><ul className="mt-4 space-y-3 text-xs leading-5 text-slate-600"><li>{t(language, 'Coverage gate and eligible role rates.', 'بوابة التغطية ومعدلات الأدوار المؤهلة.')}</li><li>{t(language, 'Pool split method and recipient counts.', 'طريقة تقسيم المجمّع وأعداد المستلمين.')}</li><li>{t(language, 'Pre-approval, approval, and payment timestamps.', 'الطوابع الزمنية للاعتماد المبدئي والاعتماد والدفع.')}</li><li>{t(language, 'Excluded recipients and payment method.', 'المستلمون المستبعدون وطريقة الدفع.')}</li></ul></section></aside></div>
  </div>;
}