// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/task-cards/CompactRow.tsx": () => import("../components/mockups/task-cards/CompactRow.tsx"),
  "./components/mockups/task-cards/PriorityHeader.tsx": () => import("../components/mockups/task-cards/PriorityHeader.tsx"),
  "./components/mockups/task-cards/TimelineStrip.tsx": () => import("../components/mockups/task-cards/TimelineStrip.tsx")
};
