// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mmp-card/OptionA.tsx": () => import("../components/mockups/mmp-card/OptionA.tsx"),
  "./components/mockups/mmp-card/OptionB.tsx": () => import("../components/mockups/mmp-card/OptionB.tsx"),
  "./components/mockups/mmp-card/OptionC.tsx": () => import("../components/mockups/mmp-card/OptionC.tsx"),
  "./components/mockups/mmp-card/OptionD.tsx": () => import("../components/mockups/mmp-card/OptionD.tsx"),
  "./components/mockups/mmp-card/OptionD1.tsx": () => import("../components/mockups/mmp-card/OptionD1.tsx"),
  "./components/mockups/mmp-card/OptionD2.tsx": () => import("../components/mockups/mmp-card/OptionD2.tsx"),
  "./components/mockups/cost-group/GroupedList.tsx": () => import("../components/mockups/cost-group/GroupedList.tsx"),
  "./components/mockups/pdm-ticker/AmberAlert.tsx": () => import("../components/mockups/pdm-ticker/AmberAlert.tsx"),
  "./components/mockups/pdm-ticker/BreakingNews.tsx": () => import("../components/mockups/pdm-ticker/BreakingNews.tsx"),
  "./components/mockups/pdm-ticker/DeadlineCountdown.tsx": () => import("../components/mockups/pdm-ticker/DeadlineCountdown.tsx"),
  "./components/mockups/pdm-ticker/DualTrack.tsx": () => import("../components/mockups/pdm-ticker/DualTrack.tsx"),
  "./components/mockups/pdm-ticker/FadeCards.tsx": () => import("../components/mockups/pdm-ticker/FadeCards.tsx"),
  "./components/mockups/pdm-ticker/HeartbeatPulse.tsx": () => import("../components/mockups/pdm-ticker/HeartbeatPulse.tsx"),
  "./components/mockups/pdm-ticker/PACTMarquee.tsx": () => import("../components/mockups/pdm-ticker/PACTMarquee.tsx"),
  "./components/mockups/pdm-ticker/RotatingSpotlight.tsx": () => import("../components/mockups/pdm-ticker/RotatingSpotlight.tsx"),
  "./components/mockups/pdm-ticker/SplitPanel.tsx": () => import("../components/mockups/pdm-ticker/SplitPanel.tsx"),
  "./components/mockups/cost-group/GroupedList.tsx": () => import("../components/mockups/cost-group/GroupedList.tsx"),
  "./components/mockups/task-cards/ActionFirst.tsx": () => import("../components/mockups/task-cards/ActionFirst.tsx"),
  "./components/mockups/task-cards/CompactRow.tsx": () => import("../components/mockups/task-cards/CompactRow.tsx"),
  "./components/mockups/task-cards/DenseChips.tsx": () => import("../components/mockups/task-cards/DenseChips.tsx"),
  "./components/mockups/task-cards/FocusMode.tsx": () => import("../components/mockups/task-cards/FocusMode.tsx"),
  "./components/mockups/task-cards/HealthDashboard.tsx": () => import("../components/mockups/task-cards/HealthDashboard.tsx"),
  "./components/mockups/task-cards/PriorityHeader.tsx": () => import("../components/mockups/task-cards/PriorityHeader.tsx"),
  "./components/mockups/task-cards/TimelineStrip.tsx": () => import("../components/mockups/task-cards/TimelineStrip.tsx")
};
