import * as XLSX from 'xlsx';
import { format } from 'date-fns';
import type { StatementRow, StatementConfig } from './financialStatementPdf';

function fmtDate(d: string | null | undefined): string {
  if (!d) return 'N/A';
  try {
    return format(new Date(d), 'MMM d, yyyy');
  } catch {
    return d;
  }
}

function fmtStatus(s: string): string {
  return s.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

function fmtCurrency(amount: number, cur: string = 'SDG'): string {
  return `${cur} ${amount.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;
}

export function generateFinancialStatementExcel(
  rows: StatementRow[],
  config: StatementConfig
): void {
  if (rows.length === 0) return;

  const cur = config.currency || 'SDG';
  const isTransport = config.statementType === 'transport_advance';
  const refNum = `STMT-${format(new Date(), 'yyyyMMdd-HHmm')}`;

  const totalRequested = rows.reduce((s, r) => s + r.requestedAmount, 0);
  const totalApproved = rows.reduce((s, r) => s + r.approvedAmount, 0);
  const totalPaid = rows.reduce((s, r) => s + r.paidAmount, 0);

  const statusLabel = fmtStatus(config.statusFilter);
  const typeLabel = isTransport ? 'Transport-Advance' : 'Operational-Cost';

  const headerRows: any[][] = [
    ['PACT Command Center  |  Financial Statement'],
    [`${config.title}  —  ${statusLabel} Statement`],
    [`Statement Reference: ${refNum}`],
    [`Generated: ${format(new Date(), 'MMM d, yyyy | HH:mm')}`],
    ...(config.generatedBy ? [[`Generated By: ${config.generatedBy}`]] : []),
    ...(config.dateRange?.from || config.dateRange?.to
      ? [[`Statement Period: ${config.dateRange?.from ? fmtDate(config.dateRange.from) : 'All'} — ${config.dateRange?.to ? fmtDate(config.dateRange.to) : 'Present'}`]]
      : []),
    [],
    ['SUMMARY'],
    ['Transactions', rows.length],
    [`Total Requested (${cur})`, fmtCurrency(totalRequested, cur)],
    [`Total Approved (${cur})`, fmtCurrency(totalApproved, cur)],
    [`Total Paid (${cur})`, fmtCurrency(totalPaid, cur)],
    [],
    ['TRANSACTION DETAILS'],
  ];

  const tableHead = isTransport
    ? ['#', 'Ref ID', 'Date', 'Requester', 'Site', `Requested (${cur})`, `Approved (${cur})`, `Paid (${cur})`, 'T1 Approver', 'T2 Approver', 'Status']
    : ['#', 'Ref ID', 'Date', 'Requester', 'Category', `Amount (${cur})`, `Approved (${cur})`, 'T1 Approver', 'T2 Approver', 'Status'];

  const tableRows = rows.map((r, idx) => {
    const row: any[] = [
      idx + 1,
      r.refId,
      fmtDate(r.date),
      r.requester || '',
    ];
    if (isTransport) {
      row.push(
        r.site || r.description || '',
        fmtCurrency(r.requestedAmount, cur),
        fmtCurrency(r.approvedAmount, cur),
        fmtCurrency(r.paidAmount, cur),
      );
    } else {
      row.push(
        r.category || r.description || '',
        fmtCurrency(r.requestedAmount, cur),
        fmtCurrency(r.approvedAmount, cur),
      );
    }
    row.push(
      r.t1Approver || 'N/A',
      r.t2Approver || 'N/A',
      fmtStatus(r.status),
    );
    return row;
  });

  const totalsRow = isTransport
    ? ['', '', '', '', 'TOTALS', fmtCurrency(totalRequested, cur), fmtCurrency(totalApproved, cur), fmtCurrency(totalPaid, cur), '', '', '']
    : ['', '', '', '', 'TOTALS', fmtCurrency(totalRequested, cur), fmtCurrency(totalApproved, cur), '', '', ''];

  tableRows.push(totalsRow);

  const approvedByT1 = rows.filter(r => r.t1Status === 'approved').length;
  const approvedByT2 = rows.filter(r => r.t2Status === 'approved').length;
  const rejectedCount = rows.filter(r => r.rejectionReason).length;

  const approvalSummaryRows: any[][] = [];
  if (rows.some(r => r.t1Approver || r.t2Approver)) {
    approvalSummaryRows.push([]);
    approvalSummaryRows.push(['APPROVAL SUMMARY']);
    approvalSummaryRows.push(['Tier 1 Approved', `${approvedByT1} of ${rows.length}`]);
    approvalSummaryRows.push(['Tier 2 Approved', `${approvedByT2} of ${rows.length}`]);
    if (rejectedCount > 0) {
      approvalSummaryRows.push(['Rejected', rejectedCount]);
    }
  }

  const allRows = [
    ...headerRows,
    tableHead,
    ...tableRows,
    ...approvalSummaryRows,
  ];

  const wb = XLSX.utils.book_new();

  const ws = XLSX.utils.aoa_to_sheet(allRows);

  const dataStartRow = headerRows.length;
  const dataEndRow = dataStartRow + tableRows.length;
  const colCount = tableHead.length;

  ws['!cols'] = [];
  for (let c = 0; c < colCount; c++) {
    const header = tableHead[c];
    let width = Math.max(header.length + 2, 14);
    if (c === 0) width = 6;
    if (header.includes('Ref ID')) width = 20;
    if (header.includes('Date')) width = 18;
    if (header.includes('Requester')) width = 24;
    if (header.includes('Site') || header.includes('Category')) width = 24;
    if (header.includes('Requested') || header.includes('Approved') || header.includes('Paid') || header.includes('Amount')) width = 20;
    if (header.includes('T1') || header.includes('T2')) width = 18;
    if (header === 'Status') width = 18;
    ws['!cols'].push({ wch: width });
  }

  ws['!merges'] = [];
  for (let r = 0; r < headerRows.length; r++) {
    if (headerRows[r].length === 1 && headerRows[r][0]) {
      ws['!merges'].push({ s: { r, c: 0 }, e: { r, c: colCount - 1 } });
    }
  }

  for (const asRow of approvalSummaryRows) {
    if (asRow.length === 1 && asRow[0]) {
      const rowIdx = allRows.indexOf(asRow);
      if (rowIdx >= 0) {
        ws['!merges'].push({ s: { r: rowIdx, c: 0 }, e: { r: rowIdx, c: colCount - 1 } });
      }
    }
  }

  XLSX.utils.book_append_sheet(wb, ws, 'Financial Statement');

  const detailData = rows.map((r, idx) => {
    const base: Record<string, any> = {
      '#': idx + 1,
      'Reference ID': r.refId,
      'Date': fmtDate(r.date),
      'Requester': r.requester,
    };

    if (isTransport) {
      base['Site'] = r.site || r.description || '';
      base['Hub'] = r.hub || '';
      base['State'] = r.state || '';
      base[`Requested (${cur})`] = r.requestedAmount;
      base[`Approved (${cur})`] = r.approvedAmount;
      base[`Paid (${cur})`] = r.paidAmount;
    } else {
      base['Category'] = r.category || '';
      base['Description'] = r.description || '';
      base[`Amount (${cur})`] = r.requestedAmount;
      base[`Approved (${cur})`] = r.approvedAmount;
    }

    base['Status'] = fmtStatus(r.status);
    base['Status (Arabic)'] = r.statusAr || '';
    base['T1 Approver'] = r.t1Approver || 'N/A';
    base['T1 Date'] = r.t1Date ? fmtDate(r.t1Date) : 'N/A';
    base['T1 Status'] = r.t1Status ? fmtStatus(r.t1Status) : 'N/A';
    base['T2 Approver'] = r.t2Approver || 'N/A';
    base['T2 Date'] = r.t2Date ? fmtDate(r.t2Date) : 'N/A';
    base['T2 Status'] = r.t2Status ? fmtStatus(r.t2Status) : 'N/A';
    base['Rejection Reason'] = r.rejectionReason || '';
    base['Notes'] = r.notes || '';

    return base;
  });

  if (detailData.length > 0) {
    const detailWs = XLSX.utils.json_to_sheet(detailData);
    const colWidths = Object.keys(detailData[0]).map(k => ({
      wch: Math.max(k.length + 2, 16),
    }));
    detailWs['!cols'] = colWidths;
    XLSX.utils.book_append_sheet(wb, detailWs, 'Full Details');
  }

  const statusClean = config.statusFilter.replace(/\s+/g, '_');
  XLSX.writeFile(wb, `${typeLabel}-Statement-${statusClean}-${format(new Date(), 'yyyy-MM-dd')}.xlsx`);
}
