-- Backfill page_role_configs for PAGE_DEFS slugs that have no DB row yet.
-- Existing rows are left untouched (Role Management / ops may have customized them).
INSERT INTO public.page_role_configs (page_slug, roles)
VALUES
  ('field-payments', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor', 'fom', 'supervisor']::text[]),
  ('cycle-exception-rollover', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('cycle-exception-resolution', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('communication-hub', ARRAY['all']::text[]),
  ('call-analytics', ARRAY['superAdmin', 'admin', 'ict']::text[]),
  ('chat', ARRAY['all']::text[]),
  ('signatures', ARRAY['superAdmin', 'admin', 'ict', 'fom', 'coordinator', 'supervisor', 'financialAdmin', 'auditor']::text[]),
  ('broadcast', ARRAY['superAdmin', 'admin']::text[]),
  ('whatsapp-admin', ARRAY['superAdmin']::text[]),
  ('mmp-full-report', ARRAY['superAdmin', 'countryDirector', 'supervisor']::text[]),
  ('project-updates', ARRAY['superAdmin', 'admin', 'fom', 'projectManager', 'coordinator', 'supervisor', 'countryDirector', 'seniorOperationsLead']::text[]),
  ('hub-operations', ARRAY['superAdmin', 'admin']::text[]),
  ('field-ops', ARRAY['superAdmin', 'admin', 'fom', 'supervisor', 'coordinator', 'dataTeam', 'seniorOperationsLead']::text[]),
  ('site-visits', ARRAY['superAdmin', 'admin', 'ict', 'fom', 'coordinator', 'supervisor', 'dataCollector', 'dataTeam', 'seniorOperationsLead']::text[]),
  ('monitoring-form', ARRAY['superAdmin', 'admin', 'dataCollector', 'coordinator', 'supervisor', 'fom']::text[]),
  ('safety-hub', ARRAY['superAdmin', 'admin', 'ict', 'fom', 'coordinator', 'supervisor', 'dataCollector', 'dataTeam']::text[]),
  ('incident-reports', ARRAY['superAdmin', 'admin', 'ict', 'fom', 'coordinator', 'supervisor', 'dataTeam']::text[]),
  ('equipment', ARRAY['superAdmin', 'admin', 'fom']::text[]),
  ('field-operation-manager', ARRAY['superAdmin', 'admin', 'fom']::text[]),
  ('coverage-map', ARRAY['superAdmin', 'admin', 'fom', 'countryDirector', 'projectManager', 'seniorOperationsLead']::text[]),
  ('coordinator-sites', ARRAY['superAdmin', 'coordinator', 'supervisor']::text[]),
  ('sites-for-verification', ARRAY['superAdmin', 'admin', 'coordinator', 'supervisor']::text[]),
  ('supervisor-sites', ARRAY['superAdmin', 'admin', 'supervisor', 'fom']::text[]),
  ('coordinator-dashboard', ARRAY['superAdmin', 'admin', 'fom', 'coordinator', 'supervisor']::text[]),
  ('monitoring-plan', ARRAY['superAdmin', 'admin', 'fom', 'coordinator', 'supervisor']::text[]),
  ('tracker-preparation', ARRAY['superAdmin', 'admin', 'fom', 'coordinator']::text[]),
  ('mmp-management', ARRAY['superAdmin', 'admin', 'ict']::text[]),
  ('finance-hub', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor', 'fom', 'countryDirector', 'seniorOperationsLead']::text[]),
  ('finance-subscriptions', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('finance', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('mobile-cost-submission', ARRAY['superAdmin', 'admin', 'supervisor', 'fom', 'coordinator', 'dataCollector']::text[]),
  ('budget-requests', ARRAY['superAdmin', 'admin', 'fom', 'financialAdmin', 'countryDirector', 'seniorOperationsLead']::text[]),
  ('wallet', ARRAY['financialAdmin', 'auditor', 'fom', 'supervisor', 'dataCollector', 'coordinator']::text[]),
  ('tier1-approvals', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor', 'supervisor', 'fom']::text[]),
  ('tier2-approvals', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('finance-processing', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('approvals', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor', 'supervisor', 'fom', 'countryDirector', 'seniorOperationsLead', 'projectManager']::text[]),
  ('approval-dashboard', ARRAY['superAdmin', 'admin', 'financialAdmin', 'supervisor', 'fom']::text[]),
  ('cost-submission-reports', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('wallet-reports', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('advance-requests-report', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('down-payment-advance-report', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('enumerator-fees-report', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('month-end-summary', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('exchange-rates', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('cost-predictions', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('reconciliation-dashboard', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('accounting-hub', ARRAY['superAdmin', 'admin', 'finance', 'financialAdmin', 'accountant', 'auditor']::text[]),
  ('accounting-coa', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('accounting-journals', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('accounting-ledger', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('accounting-trial-balance', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('accounting-bank-recon', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('accounting-fiscal-years', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('accounting-funds', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('accounting-budget', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('accounting-budget-variance', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('accounting-budget-encumbrance', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('accounting-vendors', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('accounting-purchase-req', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('accounting-purchase-orders', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('accounting-grn', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('accounting-ap-invoices', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('accounting-ap-aging', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('accounting-cheque-register', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('accounting-fixed-assets', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('accounting-depreciation', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('accounting-grants', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('accounting-cost-allocation', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('accounting-cash-flow', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('accounting-cash-flow-forecast', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('accounting-multi-currency', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('accounting-tax', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('accounting-period-close', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('accounting-donor-reports', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('accounting-sod', ARRAY['superAdmin', 'admin', 'auditor']::text[]),
  ('accounting-gl-bridge', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('accounting-consolidation', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('accounting-gl-audit', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('accounting-aml', ARRAY['superAdmin', 'admin', 'auditor']::text[]),
  ('accounting-intercompany', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('accounting-finance-dashboard', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('pre-funding', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor', 'countryDirector']::text[]),
  ('hr-hub', ARRAY['all']::text[]),
  ('hr-timesheet', ARRAY['all']::text[]),
  ('hr-payslip', ARRAY['all']::text[]),
  ('leave', ARRAY['all']::text[]),
  ('daily-work', ARRAY['all']::text[]),
  ('team-tasks', ARRAY['superAdmin', 'admin', 'fom', 'supervisor']::text[]),
  ('my-team', ARRAY['all']::text[]),
  ('my-advances', ARRAY['all']::text[]),
  ('my-expenses', ARRAY['all']::text[]),
  ('employees', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('attendance', ARRAY['superAdmin', 'admin', 'supervisor', 'fom']::text[]),
  ('offboarding', ARRAY['superAdmin', 'admin']::text[]),
  ('staff-onboarding', ARRAY['superAdmin', 'admin']::text[]),
  ('performance-reviews', ARRAY['superAdmin', 'admin', 'supervisor', 'fom']::text[]),
  ('salary-increments', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('training-certifications', ARRAY['superAdmin', 'admin', 'supervisor', 'fom']::text[]),
  ('retainer-management', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('payroll', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('positions', ARRAY['superAdmin', 'admin']::text[]),
  ('salary-retainer-report', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('crm', ARRAY['superAdmin', 'admin', 'fom', 'projectManager', 'countryDirector', 'seniorOperationsLead']::text[]),
  ('analytics-hub', ARRAY['superAdmin', 'admin', 'fom', 'countryDirector', 'projectManager', 'seniorOperationsLead']::text[]),
  ('notification-analytics', ARRAY['superAdmin', 'admin', 'ict']::text[]),
  ('data-export-center', ARRAY['superAdmin', 'admin']::text[]),
  ('data-visibility', ARRAY['superAdmin', 'admin']::text[]),
  ('reports', ARRAY['superAdmin', 'admin']::text[]),
  ('documents', ARRAY['superAdmin', 'admin', 'ict', 'financialAdmin', 'auditor']::text[]),
  ('archive', ARRAY['superAdmin', 'admin']::text[]),
  ('dct-pdm', ARRAY['superAdmin', 'admin', 'ict']::text[]),
  ('field-data', ARRAY['superAdmin', 'admin', 'fom', 'dataTeam']::text[]),
  ('executive', ARRAY['superAdmin', 'countryDirector']::text[]),
  ('surveys', ARRAY['all']::text[]),
  ('data-quality', ARRAY['superAdmin', 'admin']::text[]),
  ('questionnaire-analytics', ARRAY['superAdmin', 'admin', 'fom', 'dataTeam']::text[]),
  ('admin-hub', ARRAY['superAdmin', 'admin', 'ict']::text[]),
  ('users', ARRAY['superAdmin', 'admin', 'ict']::text[]),
  ('departments', ARRAY['superAdmin']::text[]),
  ('role-management', ARRAY['superAdmin', 'admin']::text[]),
  ('classifications', ARRAY['superAdmin', 'admin', 'financialAdmin', 'auditor']::text[]),
  ('classification-fees', ARRAY['superAdmin', 'admin']::text[]),
  ('task-admin', ARRAY['superAdmin', 'admin']::text[]),
  ('settings', ARRAY['superAdmin', 'admin']::text[]),
  ('hub-management', ARRAY['superAdmin', 'admin']::text[]),
  ('integrations', ARRAY['superAdmin', 'admin', 'ict']::text[]),
  ('permissions-management', ARRAY['superAdmin']::text[]),
  ('role-perspective', ARRAY['superAdmin', 'admin']::text[]),
  ('documentation', ARRAY['all']::text[]),
  ('mobile-documentation', ARRAY['all']::text[]),
  ('public-documentation', ARRAY['superAdmin', 'admin', 'ict']::text[]),
  ('changelog', ARRAY['superAdmin', 'admin', 'ict']::text[]),
  ('page-access', ARRAY['superAdmin']::text[]),
  ('system-diagrams', ARRAY['superAdmin']::text[]),
  ('helpline', ARRAY['superAdmin', 'admin']::text[]),
  ('support-contacts', ARRAY['superAdmin', 'admin', 'ict']::text[]),
  ('mobile-support-tickets', ARRAY['superAdmin', 'admin', 'ict']::text[]),
  ('staff-directory', ARRAY['superAdmin', 'admin']::text[]),
  ('super-admin-hub', ARRAY['superAdmin']::text[]),
  ('sa-console', ARRAY['superAdmin']::text[]),
  ('admin-monitoring', ARRAY['superAdmin']::text[]),
  ('cycle-health', ARRAY['superAdmin', 'admin']::text[]),
  ('sa-approval-dashboard', ARRAY['superAdmin', 'admin']::text[]),
  ('sa-permissions-mgmt', ARRAY['superAdmin']::text[]),
  ('sa-audit-logs', ARRAY['superAdmin', 'admin']::text[]),
  ('sa-button-registry', ARRAY['superAdmin']::text[]),
  ('sa-email-tracking', ARRAY['superAdmin', 'admin']::text[]),
  ('sa-email-management', ARRAY['superAdmin']::text[]),
  ('sa-email-preview', ARRAY['superAdmin']::text[]),
  ('sa-mobile-help', ARRAY['superAdmin']::text[]),
  ('sa-mobile-signatures', ARRAY['superAdmin']::text[]),
  ('sa-call-scheduling', ARRAY['superAdmin']::text[]),
  ('sa-doc-sync', ARRAY['superAdmin']::text[]),
  ('transaction-scanner', ARRAY['superAdmin', 'admin', 'financialAdmin']::text[]),
  ('data-management', ARRAY['superAdmin']::text[]),
  ('recycle-bin', ARRAY['superAdmin']::text[]),
  ('project-flow-stages', ARRAY['superAdmin']::text[]),
  ('hierarchy-audit', ARRAY['superAdmin', 'admin']::text[]),
  ('audit-compliance', ARRAY['superAdmin', 'admin', 'auditor']::text[]),
  ('audit-logs', ARRAY['superAdmin', 'admin', 'auditor']::text[]),
  ('login-analytics', ARRAY['superAdmin', 'admin']::text[])
ON CONFLICT (page_slug) DO NOTHING;
