-- Migration: drop mmp_payment_records
--
-- This table was the intended target for payment authorisations generated by
-- the Cycle Close Wizard's Reconciliation step (Step 5). The step was
-- converted to a read-only financial view on 2026-08-18; actual fee payments
-- are now tracked via mmp_site_entries.fee_paid_status (updated by Field
-- Payments Centre). No application code reads or writes mmp_payment_records
-- any longer — dropping it removes confusion for future queries and reports.
--
-- Safe to run at any time; IF EXISTS guard prevents failure if already dropped.

DROP TABLE IF EXISTS mmp_payment_records;
