-- =============================================================================
-- NOTICE — This migration file is SUPERSEDED.
--
-- The canonical, authoritative definitions of the pre-fund RPCs are in:
--   pre_funding_atomic_rpcs.sql   (project root)
--
-- That file defines the hardened versions with:
--   * _assert_finance_role()       — finance/admin role guard
--   * link_payment_atomically_rpc  — 11 args (p_user_id, p_receipt_url, GL posting)
--   * add_pre_fund_transaction_rpc — GL posting, optional debit/credit codes
--   * close_pre_fund_period_rpc    — period-close with carry-forward
--   * DROP of the legacy 9-arg overload of link_payment_atomically_rpc
--
-- ACTION REQUIRED:
--   Run pre_funding_atomic_rpcs.sql in the Supabase SQL Editor to install
--   (or upgrade) all pre-fund RPCs to the hardened, authoritative versions.
--
-- DO NOT add function definitions here. Always edit pre_funding_atomic_rpcs.sql.
-- =============================================================================
